# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # (Optional) Setup Node.js if using JavaScript build tools
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use the latest LTS version
          cache: 'npm' # Speeds up npm installs

      # (Optional) Install dependencies & build (if using a framework like React)
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build # Skip if using pure HTML/CSS/JS

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/' # Change if using different build folder (e.g., 'dist/')

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
